// GENERATED by scripts/build-emoji-packs.mjs — do not edit by hand.
// Source: docs/*-emojigg-pack/. Re-run the script after adding a pack.
//
// 7 packs, 80 emoji.

export type PackEmoji = { code: string; src: string };
export type EmojiPack = { slug: string; title: string; emojis: PackEmoji[] };

export const EMOJI_PACKS: EmojiPack[] = [
    {
        "slug": "discord-admin-staff-roles",
        "title": "Discord Admin Staff Roles",
        "emojis": [
            {
                "code": "deny",
                "src": "/emoji/discord-admin-staff-roles/deny.png"
            },
            {
                "code": "warnings",
                "src": "/emoji/discord-admin-staff-roles/warnings.png"
            },
            {
                "code": "moderator",
                "src": "/emoji/discord-admin-staff-roles/moderator.png"
            },
            {
                "code": "warningsdisc",
                "src": "/emoji/discord-admin-staff-roles/warningsdisc.png"
            },
            {
                "code": "moderatordisc",
                "src": "/emoji/discord-admin-staff-roles/moderatordisc.png"
            },
            {
                "code": "seniormoderator",
                "src": "/emoji/discord-admin-staff-roles/seniormoderator.png"
            },
            {
                "code": "retiredstaff",
                "src": "/emoji/discord-admin-staff-roles/retiredstaff.png"
            },
            {
                "code": "warning",
                "src": "/emoji/discord-admin-staff-roles/warning.png"
            },
            {
                "code": "trialmoderator",
                "src": "/emoji/discord-admin-staff-roles/trialmoderator.png"
            },
            {
                "code": "ingamemoderator",
                "src": "/emoji/discord-admin-staff-roles/ingamemoderator.png"
            },
            {
                "code": "tester",
                "src": "/emoji/discord-admin-staff-roles/tester.png"
            },
            {
                "code": "supporter",
                "src": "/emoji/discord-admin-staff-roles/supporter.png"
            },
            {
                "code": "contributor",
                "src": "/emoji/discord-admin-staff-roles/contributor.png"
            },
            {
                "code": "developer",
                "src": "/emoji/discord-admin-staff-roles/developer.png"
            },
            {
                "code": "remove",
                "src": "/emoji/discord-admin-staff-roles/remove.png"
            },
            {
                "code": "seniormoderatordisc",
                "src": "/emoji/discord-admin-staff-roles/seniormoderatordisc.png"
            },
            {
                "code": "add",
                "src": "/emoji/discord-admin-staff-roles/add.png"
            },
            {
                "code": "trialmoderatordisc",
                "src": "/emoji/discord-admin-staff-roles/trialmoderatordisc.png"
            },
            {
                "code": "approve",
                "src": "/emoji/discord-admin-staff-roles/approve.png"
            }
        ]
    },
    {
        "slug": "sukuna-meme-aura",
        "title": "Sukuna Meme Aura",
        "emojis": [
            {
                "code": "foxxohmph",
                "src": "/emoji/sukuna-meme-aura/foxxohmph.png"
            },
            {
                "code": "catgoodjob",
                "src": "/emoji/sukuna-meme-aura/catgoodjob.png"
            },
            {
                "code": "catnoted",
                "src": "/emoji/sukuna-meme-aura/catnoted.png"
            },
            {
                "code": "pepelovesfu",
                "src": "/emoji/sukuna-meme-aura/pepelovesfu.png"
            },
            {
                "code": "couplehuggingkissing",
                "src": "/emoji/sukuna-meme-aura/couplehuggingkissing.png"
            },
            {
                "code": "hug",
                "src": "/emoji/sukuna-meme-aura/hug.png"
            },
            {
                "code": "chug",
                "src": "/emoji/sukuna-meme-aura/chug.png"
            },
            {
                "code": "abdlfurryhi",
                "src": "/emoji/sukuna-meme-aura/abdlfurryhi.png"
            },
            {
                "code": "boykisserlove",
                "src": "/emoji/sukuna-meme-aura/boykisserlove.png"
            },
            {
                "code": "whiningdogmemehmmhmhmmm",
                "src": "/emoji/sukuna-meme-aura/whiningdogmemehmmhmhmmm.png"
            },
            {
                "code": "doggoangel",
                "src": "/emoji/sukuna-meme-aura/doggoangel.png"
            },
            {
                "code": "bubblegoober",
                "src": "/emoji/sukuna-meme-aura/bubblegoober.png"
            },
            {
                "code": "shhhhh",
                "src": "/emoji/sukuna-meme-aura/shhhhh.png"
            },
            {
                "code": "laugh",
                "src": "/emoji/sukuna-meme-aura/laugh.png"
            },
            {
                "code": "boykisserwave",
                "src": "/emoji/sukuna-meme-aura/boykisserwave.gif"
            },
            {
                "code": "blushingdogwhiningdogmemehmhmhmm",
                "src": "/emoji/sukuna-meme-aura/blushingdogwhiningdogmemehmhmhmm.png"
            },
            {
                "code": "samsungverynothappy",
                "src": "/emoji/sukuna-meme-aura/samsungverynothappy.png"
            }
        ]
    },
    {
        "slug": "penguin",
        "title": "Penguin",
        "emojis": [
            {
                "code": "beanlaugh",
                "src": "/emoji/penguin/beanlaugh.gif"
            },
            {
                "code": "bhacker",
                "src": "/emoji/penguin/bhacker.gif"
            },
            {
                "code": "hakla",
                "src": "/emoji/penguin/hakla.png"
            },
            {
                "code": "agahi",
                "src": "/emoji/penguin/agahi.gif"
            },
            {
                "code": "pikachuserve",
                "src": "/emoji/penguin/pikachuserve.png"
            },
            {
                "code": "sillyguy",
                "src": "/emoji/penguin/sillyguy.gif"
            },
            {
                "code": "agabye",
                "src": "/emoji/penguin/agabye.gif"
            }
        ]
    },
    {
        "slug": "ice-cream",
        "title": "Ice Cream",
        "emojis": [
            {
                "code": "icecream6",
                "src": "/emoji/ice-cream/icecream6.gif"
            },
            {
                "code": "icecream3",
                "src": "/emoji/ice-cream/icecream3.gif"
            },
            {
                "code": "icecream4",
                "src": "/emoji/ice-cream/icecream4.gif"
            },
            {
                "code": "icecream1",
                "src": "/emoji/ice-cream/icecream1.gif"
            },
            {
                "code": "icecream2",
                "src": "/emoji/ice-cream/icecream2.gif"
            },
            {
                "code": "icecream5",
                "src": "/emoji/ice-cream/icecream5.gif"
            }
        ]
    },
    {
        "slug": "tartaglia-1",
        "title": "Tartaglia 1",
        "emojis": [
            {
                "code": "tartagliatired",
                "src": "/emoji/tartaglia-1/tartagliatired.png"
            },
            {
                "code": "tartagliaomaewamoshindeiru",
                "src": "/emoji/tartaglia-1/tartagliaomaewamoshindeiru.png"
            },
            {
                "code": "tartaglialove",
                "src": "/emoji/tartaglia-1/tartaglialove.png"
            },
            {
                "code": "tartagliacry",
                "src": "/emoji/tartaglia-1/tartagliacry.png"
            },
            {
                "code": "tartagliasupremacy",
                "src": "/emoji/tartaglia-1/tartagliasupremacy.png"
            },
            {
                "code": "tartagliascreaminginternally",
                "src": "/emoji/tartaglia-1/tartagliascreaminginternally.png"
            },
            {
                "code": "tartagliaechhh",
                "src": "/emoji/tartaglia-1/tartagliaechhh.png"
            },
            {
                "code": "tartagliaohtsaritsa",
                "src": "/emoji/tartaglia-1/tartagliaohtsaritsa.png"
            },
            {
                "code": "tartagliaohman",
                "src": "/emoji/tartaglia-1/tartagliaohman.png"
            },
            {
                "code": "tartagliaritual",
                "src": "/emoji/tartaglia-1/tartagliaritual.png"
            },
            {
                "code": "tartagliapleeeeeeeeeeeease",
                "src": "/emoji/tartaglia-1/tartagliapleeeeeeeeeeeease.png"
            },
            {
                "code": "tartagliarizz",
                "src": "/emoji/tartaglia-1/tartagliarizz.png"
            },
            {
                "code": "tartagliagrrrr",
                "src": "/emoji/tartaglia-1/tartagliagrrrr.png"
            },
            {
                "code": "tartagliablush",
                "src": "/emoji/tartaglia-1/tartagliablush.png"
            },
            {
                "code": "tartagliawaiting",
                "src": "/emoji/tartaglia-1/tartagliawaiting.png"
            },
            {
                "code": "tartagliapleeeeeaseeee",
                "src": "/emoji/tartaglia-1/tartagliapleeeeeaseeee.png"
            },
            {
                "code": "tartagliaaaaaa2",
                "src": "/emoji/tartaglia-1/tartagliaaaaaa2.png"
            },
            {
                "code": "tartagliaaaaa3",
                "src": "/emoji/tartaglia-1/tartagliaaaaa3.png"
            },
            {
                "code": "tartagliatherapy",
                "src": "/emoji/tartaglia-1/tartagliatherapy.png"
            }
        ]
    },
    {
        "slug": "pepe",
        "title": "Pepe",
        "emojis": [
            {
                "code": "pepetyping",
                "src": "/emoji/pepe/pepetyping.gif"
            },
            {
                "code": "pepeheart",
                "src": "/emoji/pepe/pepeheart.png"
            },
            {
                "code": "pepeperfect",
                "src": "/emoji/pepe/pepeperfect.png"
            },
            {
                "code": "pepeclap",
                "src": "/emoji/pepe/pepeclap.gif"
            },
            {
                "code": "nou",
                "src": "/emoji/pepe/nou.png"
            },
            {
                "code": "pepehacker",
                "src": "/emoji/pepe/pepehacker.gif"
            }
        ]
    },
    {
        "slug": "chud-r-us",
        "title": "Chud R Us",
        "emojis": [
            {
                "code": "clockit",
                "src": "/emoji/chud-r-us/clockit.png"
            },
            {
                "code": "spray",
                "src": "/emoji/chud-r-us/spray.gif"
            },
            {
                "code": "yippeee",
                "src": "/emoji/chud-r-us/yippeee.png"
            },
            {
                "code": "chud",
                "src": "/emoji/chud-r-us/chud.png"
            },
            {
                "code": "sadqueen",
                "src": "/emoji/chud-r-us/sadqueen.png"
            },
            {
                "code": "uwu",
                "src": "/emoji/chud-r-us/uwu.png"
            }
        ]
    }
];

/** Flat lookup by code, across every pack. */
export const PACK_EMOJI_BY_CODE: Map<string, PackEmoji> = new Map(
    EMOJI_PACKS.flatMap((p) => p.emojis.map((e) => [e.code, e] as const)),
);
