/**
 * Chat emotes — the global set, plus the parser that finds them in a message.
 *
 * Two sources, one namespace:
 *   - this file's voxel set, which every channel has (art generated by
 *     scripts/build-voxel-emotes.mjs into public/emotes/voxel/)
 *   - a creator's uploads (the `customEmotes` table behind creator.getEmotes),
 *     which are merged in per-channel and win on a name collision, since a
 *     channel's own emote is the one its viewers mean.
 *
 * Emotes travel as `:code:` inside the ordinary chat text, so nothing about the
 * realtime payload changes — the DO still relays a plain string and old clients
 * degrade to showing the code.
 *
 * Codes are matched ONLY in `:colon:` form. Bare words are how Twitch and Kick
 * do it, but half this set is ordinary English (cool, sad, fire, love, dead) and
 * bare matching would eat them out of real sentences.
 */

export type Emote = {
    /** What you type, without the colons. */
    code: string;
    src: string;
    /** Extra words the picker's search should match. */
    keywords: string[];
};

/**
 * From the emoji.gg packs — built into public/emoji/ by
 * scripts/build-emoji-packs.mjs, which also emits lib/emoji/packs.generated.ts.
 * The extension is per-file (gif for the animated ones), so it's passed rather
 * than assumed.
 */
const gg = (pack: string, code: string, ext: string, ...keywords: string[]): Emote => ({
    code,
    src: `/emoji/${pack}/${code}.${ext}`,
    keywords,
});

/**
 * The default set. Order is the order the quick row shows them in, so the
 * reactions come first — those are what gets typed during a stream.
 *
 * This REPLACES the old voxel/pack art (generated SVG faces + the voxel-icon
 * object pack), which read as pixelated next to the rest of the app. Pepe and
 * Chud R Us cover the same ground the faces did — laugh, love, agree, despair —
 * which is what a stream chat actually types; the object emotes had no
 * expressions in them at all and nothing typed them.
 *
 * The wider emoji.gg catalogue is NOT here on purpose: this set is the quick
 * strip a viewer scans mid-stream, so it stays short. Everything else lives in
 * the sitewide picker (lib/emoji/packs.generated.ts).
 */
export const EMOTES: Emote[] = [
    gg("pepe", "pepeclap", "gif", "clap", "applause", "nice", "gg"),
    gg("pepe", "pepeheart", "png", "love", "heart", "like", "simp"),
    gg("pepe", "pepeperfect", "png", "perfect", "chefkiss", "based", "clean"),
    gg("pepe", "pepetyping", "gif", "typing", "wait", "brb", "writing"),
    gg("pepe", "pepehacker", "gif", "hacker", "sus", "cooking", "dev"),
    gg("pepe", "nou", "png", "no u", "nope", "deny", "cope"),

    gg("chud-r-us", "chud", "png", "chud", "guy", "npc"),
    gg("chud-r-us", "yippeee", "png", "yippee", "yay", "hype", "lets go", "celebrate"),
    gg("chud-r-us", "sadqueen", "png", "sad", "cry", "down", "rip", "sorry"),
    gg("chud-r-us", "uwu", "png", "uwu", "cute", "soft"),
    gg("chud-r-us", "clockit", "png", "clock it", "called it", "real", "facts"),
    gg("chud-r-us", "spray", "gif", "spray", "spam", "rage", "mad"),
];

const BY_CODE = new Map(EMOTES.map((e) => [e.code, e]));

/** A creator's uploaded emotes, in the shape creator.getEmotes returns. */
export type CustomEmote = { name: string; imageUrl: string };

/** Global set with a channel's own emotes merged over it. */
export function emoteSet(custom?: CustomEmote[]): Map<string, Emote> {
    if (!custom?.length) return BY_CODE;
    const merged = new Map(BY_CODE);
    for (const c of custom) {
        // Creators type these with or without colons — the schema's own example
        // is ":gigachad:" — so normalise to the bare code either way.
        const code = c.name.trim().toLowerCase().replace(/^:+|:+$/g, "");
        if (code) merged.set(code, { code, src: c.imageUrl, keywords: [] });
    }
    return merged;
}

export type ChatToken =
    | { t: "text"; v: string }
    | { t: "emote"; code: string; src: string }
    | { t: "mention"; v: string }
    | { t: "link"; v: string };

// One pass for all three inline forms. `:code:` needs at least one character;
// @handles follow the username rules used elsewhere in the app; links are
// matched loosely and validated below rather than with a strict URL grammar.
const INLINE = /(:[a-z0-9_+-]+:)|(@[a-zA-Z0-9_]{1,24})|(https?:\/\/[^\s]+)/g;

/**
 * Splits a chat line into renderable runs.
 *
 * Unknown `:codes:` fall through as plain text rather than vanishing, so a
 * channel emote that failed to load still reads as what the sender typed.
 */
export function parseChatText(text: string, set: Map<string, Emote> = BY_CODE): ChatToken[] {
    const out: ChatToken[] = [];
    let last = 0;

    const pushText = (v: string) => {
        if (!v) return;
        const prev = out[out.length - 1];
        // Merge with a preceding text run so an unmatched code doesn't split a
        // sentence into fragments the renderer has to re-join.
        if (prev?.t === "text") prev.v += v;
        else out.push({ t: "text", v });
    };

    for (const m of text.matchAll(INLINE)) {
        const [raw, emote, mention, link] = m;
        const at = m.index;

        if (emote) {
            const hit = set.get(emote.slice(1, -1).toLowerCase());
            if (!hit) continue; // leave it in the surrounding text
            pushText(text.slice(last, at));
            out.push({ t: "emote", code: hit.code, src: hit.src });
        } else if (mention) {
            pushText(text.slice(last, at));
            out.push({ t: "mention", v: mention });
        } else if (link) {
            pushText(text.slice(last, at));
            out.push({ t: "link", v: link });
        }
        last = at + raw.length;
    }

    pushText(text.slice(last));
    return out;
}

/** True when the line is nothing but emotes — those render larger, like Kick's. */
export function isEmoteOnly(tokens: ChatToken[]): boolean {
    let emotes = 0;
    for (const t of tokens) {
        if (t.t === "emote") emotes++;
        else if (t.t !== "text" || t.v.trim() !== "") return false;
    }
    return emotes > 0 && emotes <= 3;
}

/** Picker search across code and keywords. */
export function searchEmotes(query: string, set: Map<string, Emote> = BY_CODE): Emote[] {
    const q = query.trim().toLowerCase();
    const all = [...set.values()];
    if (!q) return all;
    return all.filter((e) => e.code.includes(q) || e.keywords.some((k) => k.includes(q)));
}
