/**
 * Chat emotes — the global set, plus the parser that finds them in a message.
 *
 * Two sources, one namespace:
 *   - this file's voxel set, which every channel has (art generated by
 *     scripts/build-voxel-emotes.mjs into public/emotes/voxel/)
 *   - a creator's uploads (the `customEmotes` table behind creator.getEmotes),
 *     which are merged in per-channel and win on a name collision, since a
 *     channel's own emote is the one its viewers mean.
 *
 * Emotes travel as `:code:` inside the ordinary chat text, so nothing about the
 * realtime payload changes — the DO still relays a plain string and old clients
 * degrade to showing the code.
 *
 * Codes are matched ONLY in `:colon:` form. Bare words are how Twitch and Kick
 * do it, but half this set is ordinary English (cool, sad, fire, love, dead) and
 * bare matching would eat them out of real sentences.
 */

export type Emote = {
    /** What you type, without the colons. */
    code: string;
    src: string;
    /** Extra words the picker's search should match. */
    keywords: string[];
};

/** Generated by scripts/build-voxel-emotes.mjs. */
const voxel = (code: string, ...keywords: string[]): Emote => ({
    code,
    src: `/emotes/voxel/${code}.svg`,
    keywords,
});

/** Processed out of the voxel-icon free pack by scripts/build-emote-pack.mjs. */
const pack = (code: string, ...keywords: string[]): Emote => ({
    code,
    src: `/emotes/pack/${code}.webp`,
    keywords,
});

/**
 * The default set. Order is the order the quick row shows them in, so the
 * reactions come first — those are what gets typed during a stream.
 *
 * Two origins on purpose. The pack is fifteen objects with no expressions in it
 * at all, so on its own a chat can't laugh, rage or agree; the generated faces
 * cover that and the objects cover everything else.
 */
export const EMOTES: Emote[] = [
    voxel("lol", "laugh", "funny", "lmao", "haha"),
    voxel("shock", "wow", "omg", "surprised", "pog"),
    voxel("love", "heart eyes", "adore", "simp"),
    voxel("cool", "shades", "sunglasses", "based"),
    voxel("mad", "angry", "rage", "mald"),
    voxel("sad", "cry", "sorry", "down"),
    voxel("think", "hmm", "thinking", "suspicious"),
    voxel("dead", "dying", "rip", "deceased"),
    voxel("fire", "lit", "hot", "flame", "burn"),
    voxel("heart", "love", "like"),
    voxel("coin", "money", "cash", "gm", "profit"),
    voxel("gem", "diamond", "hold", "gem stone"),

    pack("gemstone", "diamond", "jewel", "crystal"),
    pack("lock", "locked", "secure", "private"),
    pack("hourglass", "wait", "soon", "time", "patience"),
    pack("headphones", "music", "audio", "listening"),
    pack("telescope", "looking", "watch", "spotted", "searching"),
    pack("microscope", "research", "dyor", "closer look"),
    pack("toolbox", "build", "fix", "wip", "tools"),
    pack("cart", "buy", "shopping", "checkout"),
    pack("basket", "collect", "haul", "picnic"),
    pack("mailbox", "mail", "message", "inbox", "dm"),
    pack("floppy", "save", "old", "retro", "disk"),
    pack("pencil", "write", "edit", "note", "draft"),
    pack("scissors", "cut", "clip", "snip"),
    pack("teddy", "bear", "cute", "soft", "comfy"),
    pack("brick", "wall", "build", "solid"),
];

const BY_CODE = new Map(EMOTES.map((e) => [e.code, e]));

/** A creator's uploaded emotes, in the shape creator.getEmotes returns. */
export type CustomEmote = { name: string; imageUrl: string };

/** Global set with a channel's own emotes merged over it. */
export function emoteSet(custom?: CustomEmote[]): Map<string, Emote> {
    if (!custom?.length) return BY_CODE;
    const merged = new Map(BY_CODE);
    for (const c of custom) {
        // Creators type these with or without colons — the schema's own example
        // is ":gigachad:" — so normalise to the bare code either way.
        const code = c.name.trim().toLowerCase().replace(/^:+|:+$/g, "");
        if (code) merged.set(code, { code, src: c.imageUrl, keywords: [] });
    }
    return merged;
}

export type ChatToken =
    | { t: "text"; v: string }
    | { t: "emote"; code: string; src: string }
    | { t: "mention"; v: string }
    | { t: "link"; v: string };

// One pass for all three inline forms. `:code:` needs at least one character;
// @handles follow the username rules used elsewhere in the app; links are
// matched loosely and validated below rather than with a strict URL grammar.
const INLINE = /(:[a-z0-9_+-]+:)|(@[a-zA-Z0-9_]{1,24})|(https?:\/\/[^\s]+)/g;

/**
 * Splits a chat line into renderable runs.
 *
 * Unknown `:codes:` fall through as plain text rather than vanishing, so a
 * channel emote that failed to load still reads as what the sender typed.
 */
export function parseChatText(text: string, set: Map<string, Emote> = BY_CODE): ChatToken[] {
    const out: ChatToken[] = [];
    let last = 0;

    const pushText = (v: string) => {
        if (!v) return;
        const prev = out[out.length - 1];
        // Merge with a preceding text run so an unmatched code doesn't split a
        // sentence into fragments the renderer has to re-join.
        if (prev?.t === "text") prev.v += v;
        else out.push({ t: "text", v });
    };

    for (const m of text.matchAll(INLINE)) {
        const [raw, emote, mention, link] = m;
        const at = m.index;

        if (emote) {
            const hit = set.get(emote.slice(1, -1).toLowerCase());
            if (!hit) continue; // leave it in the surrounding text
            pushText(text.slice(last, at));
            out.push({ t: "emote", code: hit.code, src: hit.src });
        } else if (mention) {
            pushText(text.slice(last, at));
            out.push({ t: "mention", v: mention });
        } else if (link) {
            pushText(text.slice(last, at));
            out.push({ t: "link", v: link });
        }
        last = at + raw.length;
    }

    pushText(text.slice(last));
    return out;
}

/** True when the line is nothing but emotes — those render larger, like Kick's. */
export function isEmoteOnly(tokens: ChatToken[]): boolean {
    let emotes = 0;
    for (const t of tokens) {
        if (t.t === "emote") emotes++;
        else if (t.t !== "text" || t.v.trim() !== "") return false;
    }
    return emotes > 0 && emotes <= 3;
}

/** Picker search across code and keywords. */
export function searchEmotes(query: string, set: Map<string, Emote> = BY_CODE): Emote[] {
    const q = query.trim().toLowerCase();
    const all = [...set.values()];
    if (!q) return all;
    return all.filter((e) => e.code.includes(q) || e.keywords.some((k) => k.includes(q)));
}
