import type { UIMessage } from "ai";
import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { assistantThreads, assistantMessages } from "@/db/schema/content";

// Saving one turn of "ask chat" so the history dialog has something to list.
//
// The thread id is generated by the CLIENT and sent with every request, which
// is what keeps this a single call with no round trip: the alternative is the
// server minting an id and streaming it back as a data part, and the client
// then having to thread it into the next request before the user can send
// again. A client-chosen uuid costs nothing here because the id is always
// scoped by `userId` on read — a guessed or collided id belonging to someone
// else is unreachable, and one colliding with the caller's own thread just
// appends to their own conversation.

/** First line of the opening question, as the list label. */
function titleFrom(messages: UIMessage[]): string {
    const firstUser = messages.find((m) => m.role === "user");
    const text = firstUser?.parts
        ?.filter((p): p is { type: "text"; text: string } => p.type === "text")
        .map((p) => p.text)
        .join(" ")
        .trim();

    if (!text) return "new conversation";
    // Titles are shown on one line in a ~500px dialog; anything longer is
    // truncated by CSS anyway, and storing the whole first message as a title
    // makes the list query carry paragraphs.
    return text.length > 80 ? `${text.slice(0, 79)}…` : text;
}

/**
 * Appends the user's message and the assistant's reply to a thread, creating
 * the thread on first use.
 *
 * Only the LAST user message is written, not the whole array: the client posts
 * its full history on every turn, so everything before the last message is
 * either already stored or was replayed from storage. Writing all of them would
 * duplicate the entire conversation once per turn.
 */
export async function persistAssistantTurn({
    userId,
    threadId,
    incoming,
    responseMessage,
}: {
    userId: string;
    threadId: string;
    /** What the client posted, including the new user message. */
    incoming: UIMessage[];
    /** The assistant message produced this turn. */
    responseMessage: UIMessage;
}): Promise<void> {
    const lastUser = [...incoming].reverse().find((m) => m.role === "user");
    if (!lastUser) return;

    // Upsert: first turn creates the thread, later turns only bump updatedAt so
    // the history list orders by recency. The userId in the WHERE is what stops
    // a chosen id from writing into somebody else's thread — without it, this
    // upsert would be the one place a client-generated id could do damage.
    await db
        .insert(assistantThreads)
        .values({ id: threadId, userId, title: titleFrom(incoming) })
        .onConflictDoUpdate({
            target: assistantThreads.id,
            set: { updatedAt: new Date() },
            where: eq(assistantThreads.userId, userId),
        });

    // Verify the thread is actually ours before writing messages into it. If
    // the upsert above hit the `where` guard and did nothing (someone else's
    // id), this read returns nothing and the messages are dropped rather than
    // appended to a stranger's conversation.
    const [owned] = await db
        .select({ id: assistantThreads.id })
        .from(assistantThreads)
        .where(and(eq(assistantThreads.id, threadId), eq(assistantThreads.userId, userId)))
        .limit(1);
    if (!owned) return;

    await db.insert(assistantMessages).values([
        { threadId, role: "user", parts: lastUser.parts },
        { threadId, role: "assistant", parts: responseMessage.parts },
    ]);
}

/**
 * Best-effort wrapper. Persistence must never take down a reply that was
 * already delivered — the user has read it by the time this runs, and throwing
 * here would surface as a failed message for something that succeeded.
 */
export async function persistAssistantTurnSafely(
    args: Parameters<typeof persistAssistantTurn>[0],
): Promise<void> {
    try {
        await persistAssistantTurn(args);
    } catch (err) {
        // `.cause` specifically — drizzle reports only "Failed query: <sql>" and
        // hides the real driver message there, which on Workers is usually the
        // Date-into-sql-template error described in CLAUDE.md.
        console.error("assistant thread persist failed:", err, (err as Error)?.cause);
    }
}
