"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _wallet_btn_content from './wallet-btn-content.bones.json'
import _wallet_btn_loading from './wallet-btn-loading.bones.json'
import _wallet_btn_action from './wallet-btn-action.bones.json'
import _post_card_avatar from './post-card-avatar.bones.json'
import _post_card_name from './post-card-name.bones.json'
import _post_card_handle from './post-card-handle.bones.json'
import _post_card_line1 from './post-card-line1.bones.json'
import _post_card_line2 from './post-card-line2.bones.json'
import _post_card_action from './post-card-action.bones.json'
import _post_card_menu from './post-card-menu.bones.json'
import _post_card_bookmark from './post-card-bookmark.bones.json'
import _post_card_image from './post-card-image.bones.json'
import _shorts_video from './shorts-video.bones.json'
import _shorts_title from './shorts-title.bones.json'
import _shorts_desc from './shorts-desc.bones.json'
import _shorts_meta from './shorts-meta.bones.json'
import _shorts_avatar from './shorts-avatar.bones.json'
import _shorts_action from './shorts-action.bones.json'
import _shorts_count from './shorts-count.bones.json'
import _video_card_thumb from './video-card-thumb.bones.json'
import _video_card_avatar from './video-card-avatar.bones.json'
import _video_card_title from './video-card-title.bones.json'
import _video_card_sub from './video-card-sub.bones.json'
import _video_card_meta from './video-card-meta.bones.json'

configureBoneyard({"color":"rgba(255, 255, 255, 0.06)","darkColor":"rgba(255, 255, 255, 0.09)","animate":"shimmer"})

registerBones({
  "wallet-btn-content": _wallet_btn_content,
  "wallet-btn-loading": _wallet_btn_loading,
  "wallet-btn-action": _wallet_btn_action,
  "post-card-avatar": _post_card_avatar,
  "post-card-name": _post_card_name,
  "post-card-handle": _post_card_handle,
  "post-card-line1": _post_card_line1,
  "post-card-line2": _post_card_line2,
  "post-card-action": _post_card_action,
  "post-card-menu": _post_card_menu,
  "post-card-bookmark": _post_card_bookmark,
  "post-card-image": _post_card_image,
  "shorts-video": _shorts_video,
  "shorts-title": _shorts_title,
  "shorts-desc": _shorts_desc,
  "shorts-meta": _shorts_meta,
  "shorts-avatar": _shorts_avatar,
  "shorts-action": _shorts_action,
  "shorts-count": _shorts_count,
  "video-card-thumb": _video_card_thumb,
  "video-card-avatar": _video_card_avatar,
  "video-card-title": _video_card_title,
  "video-card-sub": _video_card_sub,
  "video-card-meta": _video_card_meta,
})
